### ISSUE TITLE
npx create-case-app script is cloning repo and lead to errors

### ISSUE THREAD

**Issue by brunobuddy** [ManifestOfficial/manifest#61]
The script is actually just clonning the [casejs/case-sta](https://github.com/casejs/case-starter) repo. 

I was working on a CASE project for a test and I accidentally commited and pushed my local project on the master branch of the starter without any asking for confirmation.

**Comment by SebConejo** [comment]
@brunobuddy Is it still relevant ?

**Comment by mohmmadAyesh** [comment]
Hello, I tried to run npx-create-case-app my-case-app and after installing dependencies and created .env file it say launching server and its remain like this for long time when I opened the folder my-case-app it show one folder with one typescript file  called admin.entity.js since it stuck at launching server step it cant run using npm start hope you fix it

**Comment by brunobuddy** [comment]
@mohmmadAyesh @SebConejo with the version of CASE (rebranded into MANIFEST for convinience) we changed the way of working: the new script is more simple

```
npx add-manifest
```
this will add the `manifest` folder with the `backend.yml` file in it. Check out [Manifest Documentation](https://manifest.build/docs) for more info.
